// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-s0buCl-3jaVXuhah-HsB8aYfHMvPQkU',
    appId: '1:929590416362:android:e243de4a7a4a3c82b31893',
    messagingSenderId: '929590416362',
    projectId: 'chat-app-1886',
    storageBucket: 'chat-app-1886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9SQFPiA8bgwQGrEZSOFxlfcQbxQ9eC24',
    appId: '1:929590416362:ios:76acc8bda51d4d86b31893',
    messagingSenderId: '929590416362',
    projectId: 'chat-app-1886',
    storageBucket: 'chat-app-1886.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9SQFPiA8bgwQGrEZSOFxlfcQbxQ9eC24',
    appId: '1:929590416362:ios:6b25d8e93a24e5a6b31893',
    messagingSenderId: '929590416362',
    projectId: 'chat-app-1886',
    storageBucket: 'chat-app-1886.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
